sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-bibtex-extra
script:
- "/bin/bash makecvTravis.sh"
deploy:
  provider: releases
  api_key:
    secure: flLVrkbUpCLecfedDMTKar+LtJzeeK5Bn3+BdWoZ98dt8j/yLG0Pkx5fzxzHA3QAH1HiLaYJ6EEAFxUrx9sn70v21ma+VkHsGRgSw2miqh3gT8wB//QYsMuj4tDx3dFC5C4bmYTymdj/8m37gTkOc92+tqx69VtG2SQ3HqXecNO/TNHgc1IUUIxqcaqIKMAF+f1LG2wPTLPI1ishxifWDZy0PlP5PdOmBxQ2DNYZHHnAEFvJU5vy56eFRW0TGv+3M8hY8Wqgs3uTeSSeHQ2SQYCthP/rAC0lbbo+g3aRbPzl3S+YsM3S18Yxkdy2jufXF2DlpAoJY2B2e7Ucvod5dyuz0dal8NLJSCxZupEjIG3+a4C4dNBoBv5b/E+k1oYy/mjmdmnHwIC5wRibZHDU8BQSitoDSfXf1tTtBc+ZdlZhi1gmtmktcL3rnW5YCCG3ZCYuWceaJawSI+2wxotsR91xHwMMUfsuH7qWtMOEFyBy3HN904FthAb/grxE7nO+XdV/WACUib0GtVfo7RE94LVyy2lLBZk9zeJtW4W536aIaw/IZINksDrw4HPEYZ7kB9eBaJ/FHiE/ekgD/hMEDkDBfGUSg2SUr/6rHLJX++VO6pM5jl2bhcSs9wfLyqVh94XKpO2MMOhXNuF/94dKX8MOXZyvo19ghJxYM1PrdK4=
  file: cv.pdf
  on:
    repo: bcaffo/cv
    all_branches: true
